# 策略文件路径，建议根据实际训练输出文件夹名称进行更新
policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/flat_htdw_4438/exported/policies/model_800.pt"
# 指向当前机器人的 MuJoCo XML 模型文件
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/htdw_4438/xml/scene.xml"

# 总仿真时长 (秒)
simulation_duration: 60.0
# 仿真步长
simulation_dt: 0.005
control_decimation: 2

# 顺序为: [FL_hip, FL_thigh, FL_calf, FR_hip, FR_thigh, FR_calf, RL_hip, RL_thigh, RL_calf, RR_hip, RR_thigh, RR_calf]
kps: [30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0] 
kds: [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]

default_angles: [0.1, 0.8, -1.5, 
                 -0.1, 0.8, -1.5, 
                 0.1, 0.8, -1.5, 
                 -0.1, 0.8, -1.5] 

# 传感器与动作缩放比例
lin_vel_scale: 2.0
ang_vel_scale: 0.25 
dof_pos_scale: 1.0 
dof_vel_scale: 0.05 
action_scale: 0.05 
cmd_scale: [2.0, 2.0, 0.25]

# 动作与观测空间维度
num_actions: 12
num_obs: 45

# 初始命令 [x速度, y速度, 偏航角速度]
cmd_init: [0.5, 0, 0]